name: Pre-commit Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: npm install
        run: npm ci --include=dev --ignore-scripts
      - name: Run Husky
        run: npx prettier --check docs
      - name: Run docusuarus build to check for broken links etc
        if: github.event_name == 'pull_request'
        run: npm run build
